"""initial schema: parcel constraints, vehicle type catalog, load plans, parcel assignments

Revision ID: 8f15dd8c9a6d
Revises: 
Create Date: 2026-08-15 22:49:20.876294
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '8f15dd8c9a6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_plans',
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('clustering_method', sa.String(length=16), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('n_parcels', sa.Integer(), nullable=False),
    sa.Column('n_vehicles', sa.Integer(), nullable=False),
    sa.Column('mean_utilization', sa.Float(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('mean_time_window_compliance', sa.Float(), nullable=False),
    sa.Column('total_fleet_cost', sa.Float(), nullable=False),
    sa.Column('hypervolume', sa.Float(), nullable=True),
    sa.Column('runtime_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_load_plans_delivery_date'), 'load_plans', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_load_plans_depot_id'), 'load_plans', ['depot_id'], unique=False)
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.String(length=64), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('time_window_start', sa.String(length=5), nullable=False),
    sa.Column('time_window_end', sa.String(length=5), nullable=False),
    sa.Column('fragile', sa.Boolean(), nullable=False),
    sa.Column('length_cm', sa.Float(), nullable=True),
    sa.Column('width_cm', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('max_stack_weight_kg', sa.Float(), nullable=False),
    sa.Column('loading_orientation_fixed', sa.Boolean(), nullable=False),
    sa.Column('hazardous', sa.Boolean(), nullable=False),
    sa.Column('hazmat_class', sa.String(length=16), nullable=True),
    sa.Column('requires_refrigeration', sa.Boolean(), nullable=False),
    sa.Column('temp_min_celsius', sa.Float(), nullable=True),
    sa.Column('temp_max_celsius', sa.Float(), nullable=True),
    sa.Column('two_person_lift', sa.Boolean(), nullable=False),
    sa.Column('do_not_tilt', sa.Boolean(), nullable=False),
    sa.Column('priority_level', sa.String(length=16), nullable=False),
    sa.Column('service_type', sa.String(length=24), nullable=False),
    sa.Column('is_noise', sa.Boolean(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('cluster_probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_delivery_date'), 'parcels', ['delivery_date'], unique=False)
    op.create_index('ix_parcels_depot_date', 'parcels', ['depot_id', 'delivery_date'], unique=False)
    op.create_index(op.f('ix_parcels_depot_id'), 'parcels', ['depot_id'], unique=False)
    op.create_index(op.f('ix_parcels_parcel_id'), 'parcels', ['parcel_id'], unique=True)
    op.create_table('vehicle_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('max_weight_kg', sa.Float(), nullable=False),
    sa.Column('max_length_cm', sa.Float(), nullable=False),
    sa.Column('max_width_cm', sa.Float(), nullable=False),
    sa.Column('max_height_cm', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_capabilities_name'), 'vehicle_capabilities', ['name'], unique=True)
    op.create_table('vehicle_type_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('capacity_m3', sa.Float(), nullable=False),
    sa.Column('cargo_length_cm', sa.Float(), nullable=False),
    sa.Column('cargo_width_cm', sa.Float(), nullable=False),
    sa.Column('cargo_height_cm', sa.Float(), nullable=False),
    sa.Column('max_parcels', sa.Integer(), nullable=False),
    sa.Column('max_stack_layers', sa.Integer(), nullable=False),
    sa.Column('fixed_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_km', sa.Float(), nullable=False),
    sa.Column('avg_speed_kmh', sa.Float(), nullable=False),
    sa.Column('is_refrigerated', sa.Boolean(), nullable=False),
    sa.Column('temp_min_celsius', sa.Float(), nullable=True),
    sa.Column('temp_max_celsius', sa.Float(), nullable=True),
    sa.Column('is_hazmat_certified', sa.Boolean(), nullable=False),
    sa.Column('has_tail_lift', sa.Boolean(), nullable=False),
    sa.Column('min_road_width_m', sa.Float(), nullable=True),
    sa.Column('depot_id', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_type_catalog_code'), 'vehicle_type_catalog', ['code'], unique=True)
    op.create_table('virtual_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('virtual_vehicle_id', sa.String(length=64), nullable=False),
    sa.Column('depot_id', sa.String(length=32), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('capacity_m3', sa.Float(), nullable=False),
    sa.Column('used_weight_kg', sa.Float(), nullable=False),
    sa.Column('used_volume_m3', sa.Float(), nullable=False),
    sa.Column('parcel_count', sa.Integer(), nullable=False),
    sa.Column('max_parcels', sa.Integer(), nullable=True),
    sa.Column('estimated_distance_km', sa.Float(), nullable=False),
    sa.Column('time_window_compliance', sa.Float(), nullable=True),
    sa.Column('fleet_cost', sa.Float(), nullable=True),
    sa.Column('is_refrigerated', sa.Boolean(), nullable=False),
    sa.Column('is_hazmat_certified', sa.Boolean(), nullable=False),
    sa.Column('cargo_length_cm', sa.Float(), nullable=True),
    sa.Column('cargo_width_cm', sa.Float(), nullable=True),
    sa.Column('cargo_height_cm', sa.Float(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('destination_latitude', sa.Float(), nullable=True),
    sa.Column('destination_longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['load_plans.plan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_vehicles_delivery_date'), 'virtual_vehicles', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_virtual_vehicles_depot_id'), 'virtual_vehicles', ['depot_id'], unique=False)
    op.create_index(op.f('ix_virtual_vehicles_plan_id'), 'virtual_vehicles', ['plan_id'], unique=False)
    op.create_index(op.f('ix_virtual_vehicles_virtual_vehicle_id'), 'virtual_vehicles', ['virtual_vehicle_id'], unique=True)
    op.create_table('parcel_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('virtual_vehicle_id', sa.String(length=64), nullable=False),
    sa.Column('parcel_id', sa.String(length=64), nullable=False),
    sa.Column('delivery_sequence', sa.Integer(), nullable=False),
    sa.Column('load_sequence', sa.Integer(), nullable=False),
    sa.Column('stack_layer', sa.Integer(), nullable=False),
    sa.Column('load_position_x', sa.Float(), nullable=False),
    sa.Column('load_position_y', sa.Float(), nullable=False),
    sa.Column('load_position_z', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.parcel_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['load_plans.plan_id'], ),
    sa.ForeignKeyConstraint(['virtual_vehicle_id'], ['virtual_vehicles.virtual_vehicle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_assignments_parcel_id'), 'parcel_assignments', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_parcel_assignments_plan_id'), 'parcel_assignments', ['plan_id'], unique=False)
    op.create_index(op.f('ix_parcel_assignments_virtual_vehicle_id'), 'parcel_assignments', ['virtual_vehicle_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcel_assignments_virtual_vehicle_id'), table_name='parcel_assignments')
    op.drop_index(op.f('ix_parcel_assignments_plan_id'), table_name='parcel_assignments')
    op.drop_index(op.f('ix_parcel_assignments_parcel_id'), table_name='parcel_assignments')
    op.drop_table('parcel_assignments')
    op.drop_index(op.f('ix_virtual_vehicles_virtual_vehicle_id'), table_name='virtual_vehicles')
    op.drop_index(op.f('ix_virtual_vehicles_plan_id'), table_name='virtual_vehicles')
    op.drop_index(op.f('ix_virtual_vehicles_depot_id'), table_name='virtual_vehicles')
    op.drop_index(op.f('ix_virtual_vehicles_delivery_date'), table_name='virtual_vehicles')
    op.drop_table('virtual_vehicles')
    op.drop_index(op.f('ix_vehicle_type_catalog_code'), table_name='vehicle_type_catalog')
    op.drop_table('vehicle_type_catalog')
    op.drop_index(op.f('ix_vehicle_capabilities_name'), table_name='vehicle_capabilities')
    op.drop_table('vehicle_capabilities')
    op.drop_index(op.f('ix_parcels_parcel_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_depot_id'), table_name='parcels')
    op.drop_index('ix_parcels_depot_date', table_name='parcels')
    op.drop_index(op.f('ix_parcels_delivery_date'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_load_plans_depot_id'), table_name='load_plans')
    op.drop_index(op.f('ix_load_plans_delivery_date'), table_name='load_plans')
    op.drop_table('load_plans')
    # ### end Alembic commands ###
