import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { Download, PackageOpen } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { Card, DataTable, EmptyState, InlineAlert, LoadingState, PageHeader, PrimaryButton, StatusBadge } from '../components/UI'
import { optimizationService } from '../services/optimizationService'
import type { LoadPlan } from '../types'
import { formatNumber, formatPercent } from '../utils/format'
import { CargoBay3D } from '../components/CargoBay3D'
import type { CargoColorMode } from '../components/CargoBay3D'

type SortKey = 'delivery_sequence' | 'load_sequence' | 'weight_kg'

export function LoadPlanPage() {
  const { planId = '' } = useParams()
  const navigate = useNavigate()
  const [planInput, setPlanInput] = useState(planId)
  const [plan, setPlan] = useState<LoadPlan | null>(null)
  const [selectedVehicle, setSelectedVehicle] = useState('')
  const [sortKey, setSortKey] = useState<SortKey>('load_sequence')
  const [view, setView] = useState<'table' | '3d'>('table')
  const [colorMode, setColorMode] = useState<CargoColorMode>('sequence')
  const [maxLoadSequence, setMaxLoadSequence] = useState(0)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    const timer = window.setTimeout(() => {
      if (!planId) { setPlan(null); return }
      setPlanInput(planId); setLoading(true); setError('')
      optimizationService.getPlan(planId)
      .then((response) => { setPlan(response); setSelectedVehicle(response.vehicles[0]?.virtual_vehicle_id ?? ''); setMaxLoadSequence(response.vehicles[0]?.parcels.length ?? 0) })
        .catch((err) => setError(err instanceof Error ? err.message : 'Failed to load plan.'))
        .finally(() => setLoading(false))
    }, 0)
    return () => window.clearTimeout(timer)
  }, [planId])

  const vehicle = plan?.vehicles.find((row) => row.virtual_vehicle_id === selectedVehicle)
  const parcels = useMemo(() => [...(vehicle?.parcels ?? [])].sort((a, b) => a[sortKey] - b[sortKey]), [vehicle, sortKey])
  const openPlan = (event: FormEvent) => { event.preventDefault(); if (planInput.trim()) navigate(`/load-plans/${encodeURIComponent(planInput.trim())}`) }

  return <div>
    <PageHeader title="Load Plan" description="Vehicle-by-vehicle loading instructions generated by the optimizer." action={plan && <a className="inline-flex items-center gap-2 rounded-xl bg-fleet-blue px-4 py-2.5 text-sm font-extrabold text-white" href={optimizationService.planCsvUrl(plan.plan_id)}><Download className="h-4 w-4" />Export CSV</a>} />
    <Card className="mb-5"><form className="flex flex-col gap-3 sm:flex-row" onSubmit={openPlan}><input aria-label="Plan ID" className="focus-ring flex-1 rounded-xl border border-fleet-line px-4 py-2.5" onChange={(e) => setPlanInput(e.target.value)} placeholder="PLAN-…" value={planInput} /><PrimaryButton type="submit">Open plan</PrimaryButton></form></Card>
    {loading && <LoadingState message="Please wait while the load plan is prepared…" />}
    {error && <InlineAlert tone="error">{error}</InlineAlert>}
    {!loading && !error && !planId && <EmptyState icon={PackageOpen} title="Enter a plan ID" description="Open a plan created on the Load Optimization page." />}
    {plan && !loading && <>
      <div className="mb-5 grid gap-3 md:grid-cols-5"><Summary label="Plan" value={plan.plan_id} /><Summary label="Parcels" value={formatNumber(plan.n_parcels)} /><Summary label="Vehicles" value={formatNumber(plan.n_vehicles)} /><Summary label="Mean utilization" value={formatPercent(plan.mean_utilization)} /><Summary label="Cost / parcel" value={`LKR ${formatNumber(plan.cost_per_parcel)}`} /></div>
      <Card className="mb-5" title="Vehicle selection"><div className="grid gap-4 md:grid-cols-2">
        <label className="text-sm font-bold">Vehicle<select className="mt-1 block w-full rounded-xl border border-fleet-line px-3 py-2.5" value={selectedVehicle} onChange={(e) => { const id = e.target.value; setSelectedVehicle(id); setMaxLoadSequence(plan.vehicles.find((row) => row.virtual_vehicle_id === id)?.parcels.length ?? 0) }}>{plan.vehicles.map((row) => <option key={row.virtual_vehicle_id} value={row.virtual_vehicle_id}>{row.virtual_vehicle_id} · {row.vehicle_type} · {row.parcel_count} parcels</option>)}</select></label>
        <label className="text-sm font-bold">Sort parcels<select className="mt-1 block w-full rounded-xl border border-fleet-line px-3 py-2.5" value={sortKey} onChange={(e) => setSortKey(e.target.value as SortKey)}><option value="load_sequence">Load sequence</option><option value="delivery_sequence">Delivery sequence</option><option value="weight_kg">Weight</option></select></label>
      </div>{vehicle && <div className="mt-4 flex flex-wrap gap-2"><StatusBadge>{vehicle.vehicle_type}</StatusBadge><StatusBadge tone="green">{formatNumber(vehicle.used_weight_kg)} / {formatNumber(vehicle.capacity_kg)} kg</StatusBadge><StatusBadge tone="slate">Bay {vehicle.cargo_length_cm} × {vehicle.cargo_width_cm} × {vehicle.cargo_height_cm} cm</StatusBadge></div>}</Card>
      <div className="mb-4 inline-flex rounded-xl border border-fleet-line bg-white p-1"><button className={`rounded-lg px-4 py-2 text-sm font-bold ${view === 'table' ? 'bg-fleet-blue text-white' : ''}`} onClick={() => setView('table')} type="button">Loading table</button><button className={`rounded-lg px-4 py-2 text-sm font-bold ${view === '3d' ? 'bg-fleet-blue text-white' : ''}`} onClick={() => setView('3d')} type="button">3D cargo bay</button></div>
      {view === 'table' && (parcels.length === 0 ? <EmptyState icon={PackageOpen} title="No parcel assignments" description="This vehicle has no persisted parcels." /> : <DataTable headers={['Load', 'Delivery', 'Parcel', 'Weight', 'Dimensions', 'Layer', 'Position', 'Handling']}>{parcels.map((parcel) => <tr className="border-t border-fleet-line" key={parcel.parcel_id}><td className="px-5 py-3 font-bold">{parcel.load_sequence}</td><td className="px-5 py-3">{parcel.delivery_sequence}</td><td className="px-5 py-3 font-mono text-xs">{parcel.parcel_id}</td><td className="px-5 py-3">{parcel.weight_kg.toFixed(1)} kg</td><td className="px-5 py-3">{parcel.length_cm} × {parcel.width_cm} × {parcel.height_cm} cm</td><td className="px-5 py-3">{parcel.stack_layer}</td><td className="px-5 py-3 font-mono text-xs">({parcel.load_position_x}, {parcel.load_position_y}, {parcel.load_position_z})</td><td className="px-5 py-3">{parcel.fragile ? <StatusBadge tone="amber">Fragile</StatusBadge> : parcel.stackable ? 'Stackable' : 'Top only'}</td></tr>)}</DataTable>)}
      {view === '3d' && vehicle && <Card><div className="mb-4 grid gap-4 md:grid-cols-[220px_1fr]"><label className="text-sm font-bold">Color by<select className="mt-1 block w-full rounded-xl border border-fleet-line px-3 py-2" value={colorMode} onChange={(e) => setColorMode(e.target.value as CargoColorMode)}><option value="sequence">Load sequence</option><option value="weight">Weight</option><option value="layer">Stack layer</option></select></label><label className="text-sm font-bold">Load progress: {maxLoadSequence} / {vehicle.parcels.length}<input aria-label="Load sequence progress" className="mt-3 block w-full accent-blue-600" max={vehicle.parcels.length} min={0} onChange={(e) => setMaxLoadSequence(Number(e.target.value))} type="range" value={Math.min(maxLoadSequence, vehicle.parcels.length)} /></label></div><CargoBay3D maxLoadSequence={maxLoadSequence} mode={colorMode} vehicle={vehicle} /></Card>}
    </>}
  </div>
}

function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-fleet-line bg-white p-4 shadow-card"><div className="text-xs font-black uppercase tracking-wide text-fleet-muted">{label}</div><div className="mt-1 truncate text-xl font-black">{value}</div></div> }
